// Generated by CoffeeScript 1.6.2
(function() {
  var Xml, fs, mydoc, xmldoc;

  Xml = require('./xml');

  fs = require('fs');

  mydoc = fs.readFileSync('profind_request.xml');

  xmldoc = mydoc.toString();

  Xml.loadDOMDocument(xmldoc, null, function(err, dom) {
    var c, firstChild, lg;

    firstChild = dom.firstChild;
    c = firstChild.childNodes;
    lg = c.length;
    return console.log(lg);
  });

}).call(this);
