// Generated by CoffeeScript 1.6.2
(function() {
  var board, client, client_settings, five, mosca_host, mosca_port, mqtt, reg, tab;

  five = require("johnny-five");

  mqtt = require('mqtt');

  mosca_host = 'localhost';

  mosca_port = '1883';

  client_settings = {
    keepalive: 1000,
    protocolId: 'MQIsdp',
    protocolVersion: 3,
    clientId: 'client-ard'
  };

  board = new five.Board();

  client = mqtt.createClient(mosca_port, mosca_host, client_settings);

  reg = /(\w+):(\d+)/;

  tab = reg.exec("vertical:123");

  board.on("ready", function() {
    var myLed, myServoX, myServoY;

    myServoX = new five.Servo(9);
    myServoY = new five.Servo({
      pin: 8,
      range: [70, 115]
    });
    myLed = new five.Led(7);
    client.subscribe('laser/cat');
    client.on('message', function(topic, message) {
      var ordre, too;

      console.log('received', topic, message);
      console.log(typeof message);
      tab = reg.exec(message);
      ordre = tab[1];
      too = tab[2];
      console.log(ordre);
      console.log(too);
      if (ordre === "axex") {
        myServoX.to(too);
      }
      if (ordre === "axey") {
        myServoY.to(too);
      }
      if (ordre === "laser") {
        if (too === '1') {
          myLed.on();
        } else {
          myLed.off();
        }
      }
      console.log(typeof too);
      return myServoY.to(too);
    });
    myLed.on();
    myServoY.center();
    return myServoX.center();
  });

}).call(this);
